### ISSUE TITLE
Palace Midas freezes

### ISSUE THREAD

**Issue by andrewsyc** [XProger/OpenLara#116]
Weird bugs on some levels. Palace Midas freezes a lot, especially when entering the room with the switches and pillars for both PSX and PHD file.

Uncaught abort(4) at Error
    at jsStackTrace (http://xproger.info/projects/OpenLara/OpenLara_wasm.js:1185:12)
    at stackTrace (http://xproger.info/projects/OpenLara/OpenLara_wasm.js:1199:21)
    at abort (http://xproger.info/projects/OpenLara/OpenLara_wasm.js:9294:43)
    at $p4 (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:87561:1)
    at $em (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:47334:36)
    at $e_ (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:54423:1)
    at $dm (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:32915:1)
    at $ec (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:45518:29)
    at $dm (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:32853:1)
    at $eT (blob:http://xproger.info/3aea2a42-ecca-42db-bbf8-3eda59af1721:53381:9)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by XProger** [comment]
fixed d6e1d42927d2769fad83cad2d07196f1bcb3a610
